import dotenv from "dotenv"
dotenv.config();

const ENVIRONMENT_VARIABLES = {
  DATABASE_HOST: "DATABASE_HOST",
  DATABASE_NAME: "DATABASE_NAME",
  DATABASE_USERNAME: "DATABASE_USERNAME",
  DATABASE_PORT: "DATABASE_PORT",
  SERVER_PORT: "SERVER_PORT",
  DATABASE_PASSWORD: "DATABASE_PASSWORD",
  NODE_ENV: "NODE_ENV",
  JWT_SECRET: "JWT_SECRET",
  JWT_ISSUER: "JWT_ISSUER",
  INTER_SERVICE_SECRET: "INTER_SERVICE_SECRET",
  RABBIT_MQ_URL: "RABBIT_MQ_URL",
}

function getEnv(variableName) {
    const envKey = ENVIRONMENT_VARIABLES[variableName]
    const foundEnv = process.env[envKey]
    const message = `${envKey} was not found!`;
    if (!foundEnv) {
        console.log(message)
        throw Error(message)
    }
    return foundEnv
}

export const APP_CONFIGS = {
  DATABASE_NAME: getEnv(ENVIRONMENT_VARIABLES.DATABASE_NAME),
  DATABASE_USERNAME: getEnv(ENVIRONMENT_VARIABLES.DATABASE_USERNAME),
  DATABASE_PORT: getEnv(ENVIRONMENT_VARIABLES.DATABASE_PORT),
  DATABASE_PASSWORD: getEnv(ENVIRONMENT_VARIABLES.DATABASE_PASSWORD),
  DATABASE_HOST: getEnv(ENVIRONMENT_VARIABLES.DATABASE_HOST),
  SERVER_PORT: getEnv(ENVIRONMENT_VARIABLES.SERVER_PORT),
  NODE_ENV: getEnv(ENVIRONMENT_VARIABLES.NODE_ENV),
  IS_PRODUCTION:
    getEnv(ENVIRONMENT_VARIABLES.NODE_ENV) === "production" ||
    getEnv(ENVIRONMENT_VARIABLES.NODE_ENV) === "prod",
  API_KEY_EXPIRES_AT: 12 * 60 * 60 * 1000, // 12hr
  JWT: {
    MAIN_SECRET: getEnv(ENVIRONMENT_VARIABLES.JWT_SECRET),
    ISSUER: getEnv(ENVIRONMENT_VARIABLES.JWT_ISSUER),
  },
  RABBIT_MQ: {
    URL: getEnv(ENVIRONMENT_VARIABLES.RABBIT_MQ_URL),
  },
  INTER_SERVICE_SECRET: getEnv(ENVIRONMENT_VARIABLES.INTER_SERVICE_SECRET),
};